Investor.Web/Controllers/BlogController.cs
using System.Linq;
using Investor.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Investor.Model;

namespace Investor.Web.Controllers
{
    //[Authorize(Roles = "bloger")]
    public class BlogController : Controller
    { 
        private readonly IBlogService _blogService;
        private readonly INewsService _newsService;
        private readonly IUserService _userService;
        private readonly ITagService _tagService;

        public BlogController(IBlogService blogService, IUserService userService, ITagService tagService, INewsService newsService)
        {
            _blogService = blogService;
            _userService = userService;
            _tagService = tagService;
            _newsService = newsService;
        }

        public IActionResult Index()
        {
            ViewBag.IsBlog = true;
            ViewBag.PopularTags = _tagService.GetPopularTagsAsync(5).Result.ToList();
            ViewBag.PopularBlogers = _blogService.GetPopularUsers(10).Result.ToList(); ;
            ViewBag.LatestPosts = _newsService.GetLatestNewsAsync(20).Result.ToList(); 
            ViewBag.LatestBlogs = _blogService.GetLatestBlogsAsync<BlogPreview>().Result.ToList();
            ViewBag.PopularBlogs = _blogService.GetPopularBlogsAsync().Result.ToList();
            ViewBag.Blogers = _userService.GetDictionaryOfBlogersAsync().Result;
            return View();
        }

        public IActionResult Page(int id)
        {
            ViewBag.PathBase = Request.Host.Value;
            var blogs = _blogService.GetBlogByIdAsync<Blog>(id).Result;
            ViewBag.Post = blogs;
            ViewBag.LatestPosts = _newsService.GetLatestNewsAsync(10).Result.ToList();           
            ViewBag.Tags = _tagService.GetPopularTagsAsync(5).Result.ToList();
            return View("Single/BlogPage");
        }

        public IActionResult BlogerPage(string id)
        {
            User bloger = _userService.GetUserByNickName(id).Result;
            ViewBag.Blogs = _blogService.GetBlogsByUserIdAsync(bloger.Id).Result.ToList();
            ViewBag.LatestPosts = _newsService.GetLatestNewsAsync(5).Result.ToList();
            ViewBag.IsBlog = true;
            return View("Bloger/BlogerPage", bloger);
        }
    }
}

Investor.Web/Controllers/SearchController.cs
using System;
using System.Linq;
using Investor.Model;
using Investor.Service.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace Investor.Web.Controllers
{
    public class SearchController : Controller
    {
        private readonly ISearchService _searchService;
        private readonly ICategoryService _categoryService;

        public SearchController(ISearchService searchService, ICategoryService categoryService)
        {
            _searchService = searchService;
            _categoryService = categoryService;
        }

        [HttpGet]
        public IActionResult Posts(int page = 1, int count = 10, string categoryUrl = null, string query = null, string date = null)
        {
            DateTime? dt = null;
            if (!String.IsNullOrEmpty(date))
            {
                dt = DateTime.Parse(date);
            }
            var postQuery = new PostSearchQuery
            {
                CategoryUrl = categoryUrl,
                Count = count,
                Date = dt,
                Page = page,
                Query = query,
            };

            ViewBag.CategoryName = _categoryService.GetCategoryByUrlAsync(categoryUrl).Result;
            ViewBag.Query = postQuery;
            var searchResult = _searchService.SearchPosts(postQuery).Result.ToList();

            return View("Index", searchResult);
        }

        public IActionResult SearchByTag(string tag, string categoryUrl)
        {
            ViewBag.CategoryName = _categoryService.GetCategoryByUrlAsync(categoryUrl).Result;
            var postQuery = new PostSearchQuery { Tag = tag, CategoryUrl = categoryUrl };
            ViewBag.Query = postQuery;
            var searchResult = _searchService.SearchPosts(postQuery).Result.ToList();
            return View(searchResult);
        }
    }
}

Investor.Web/Views/Blog/Index.cshtml
@using Investor.Model
@using Investor.Model.Views
<section class="page-blog">
    <div class="container">
        <div class="row">
            <div class="block-border-top blog-border-color top-blog">
                <div class="offset-p">
                    <h1 class="title-block">Топ блогерів</h1>
                    @Html.Partial("_BlogersCarrouselTemplate", ViewBag.PopularBlogers as List<PopularUserViewModel>)
                </div>
            </div>

            <div class="col-lg-8 pl-0 p-0 pr-lg-2">
                <!--Popular blogs-->
                <div class="body-block block-border-top blog-border-color mb-4">
                    <h1 class="title-block">Популярні блоги</h1>
                    @Html.Partial("_PopularBlogsTemplate",ViewBag.PopularBlogs as IEnumerable<BlogPreview>)

                </div>
                <!--end popular blogs-->
                <!--Recent recent-->
                <div class="block-recent-recent">
                    <div class="body-block block-border-top blog-border-color mb-3 last-blogs-wrapper">
                        <h2 class="title-block">Останні записи</h2>
                        @Html.Partial("_LastBlogsTemplate", ViewBag.LatestBlogs as IEnumerable<BlogPreview>)
                    </div>
                    <div class="wrapper-btn-more">
                        <a href="#" class="btn-more lastblogs text-center"><span class="circle circle-blog-color"><i class="icons icon-arrow-down"></i></span>Більше новин</a>
                    </div>
                </div>

                <div class="body-block block-border-top blog-border-color mb-4">
                    <h2 class="title-block">Всі блогери</h2>
                    @Html.Partial("_AllBlogersTemplate", ViewBag.Blogers as SortedDictionary<string, List<User>>)
                </div>
                <!--end recent recent-->
            </div>

            <div class="col-lg-4 pl-lg-2  p-0 pr-0">

                <div class="block-border-top blog-border-color last-news blog-tags mb-3">
                    <h2 class="title-block">Популярні теги</h2>
                    @Html.Partial("_PopularBlogsTagsTemplate", ViewBag.PopularTags as IEnumerable<Tag>)
                </div>
                   @Html.Partial("_LastNewsPreviewTemplate", ViewBag.LatestPosts as IEnumerable<PostPreview>)
            </div>

        </div>
    </div>

</section>

Investor.Web/Views/Blog/_AllBlogersTemplate.cshtml
@using Investor.Model
@model SortedDictionary<string, List<User>>
<div class="wrapper-all-bloggers grid">
    @foreach (var blogers in Model)
    {
        <div class="item-blogger grid-item col-6 col-md-4 mb-4">
            <p class="letter">@blogers.Key.ToUpper()</p>
            @foreach (User bloger in blogers.Value)
            {
            <ul class="wrapper-name-blogger">
                <li><a href="/blog/blogerpage/@bloger.UserName" class="name-blogger">@(bloger.Surname + " " + bloger.Name)</a></li>
            </ul>
            }
        </div>
    }
</div>

Investor.Web/Views/Blog/_BlogersCarrouselTemplate.cshtml
@model List<Investor.Model.Views.PopularUserViewModel>
@inject Investor.Service.Utils.Interfaces.IImagePathService ImagePath
<div class="carousel-top-blog slick-carousel">
    @for (int i = 0; i < Model.Count() / 3 + (Model.Count() % 3 > 0 ? 1 : 0); i++)
    {
        <div class="colum-slider">
            @for (int jIndex = i * 3; jIndex < i * 3 + 3 && jIndex < Model.Count(); jIndex++)
            {
                <div class="sidebar-item-blog vertical">
                    <a href="/blog/blogerpage/@Model[jIndex].User.UserName">
                        <img src="~/@ImagePath.GetAccountImagePath(Model[jIndex].User.Photo)" alt="" class="rounded-circle align-top">
                    </a>
                    <div class="sidebar-item-blog-body align-top">
                        <a class="author-blog" href="/blog/blogerpage/@Model[jIndex].User.UserName">
                            @Model[jIndex].User.Name  @Model[jIndex].User.Surname
                        </a>
                        <a href="/blog/page/@Model[jIndex].PostId" class="title-blog">
                            @Model[jIndex].Title
                        </a>
                        <span class="activity-level blog-today-color">Рівень активності @Model[jIndex].NumberOfPosts</span>
                    </div>
                </div>
            }
        </div>
    }
</div>
<span class="paging-info paging-blog"></span>

Investor.Web/Views/Blog/_LastBlogsTemplate.cshtml
@using Investor.Model
@model IEnumerable<BlogPreview>

<input hidden class="numberOfPosts" value="@Model.Count()" />
@foreach (var blog in Model)
{
    @Html.Partial("~/Views/Blog/_LatestBlogPreviewTemplate.cshtml", blog)
}

Investor.Web/Views/Blog/_LatestBlogPreviewTemplate.cshtml
@using Investor.Model
@model BlogPreview
@inject Investor.Service.Utils.TimeService PostPublicationDate
@inject Investor.Service.Utils.Interfaces.IImagePathService ImagePath

<div class="item-blog-news col-12">
    <div class="img-news">
        <a href="/blog/page/@Model.PostId">
            <img src="~/@ImagePath.GetImagePath(Model.Image, Model.PostId, "small-")" class="img-fluid rounded-circle">
        </a>
    </div>
    <div class="body-all-news">
        <a href="/blog/page/@Model.PostId" class="title-news">@Model.Title</a>
        <p class="text-news brief-description">@Model.Description</p>
        <span class="blog-today-color data-blog">@PostPublicationDate.GetFormattedDate(Model.PublishedOn)</span>
        <a href="/blog/blogerpage/@Model.Author.UserName" class="user-publish ml-3">
            <img src="~/@ImagePath.GetAccountImagePath(Model.Author.Photo)" class="photo-img rounded-circle" />@Model.Author.Name
        </a>
    </div>
</div>

Investor.Web/Views/Blog/_PopularBlogsTagsTemplate.cshtml
@model IEnumerable<Investor.Model.Tag>

<div class="wrapper-tag-news">
    @foreach (var tag in Model)
    {
        <a asp-action="SearchByTag" asp-controller="Search" asp-route-tag="@tag.Name" class="tag-item">@tag.Name</a>
    }
</div>

Investor.Web/Views/Blog/_PopularBlogsTemplate.cshtml
@using Investor.Model    
@model IEnumerable<BlogPreview>

@foreach (var blog in Model)
{
    @Html.Partial("_LatestBlogPreviewTemplate", blog)
}